POST localhost:8000/deposit?username=admin&password=admin&amount=100&token=USD
Content-Type: application/json

{
  "username": "admin",
  "password": "admin",
  "amount": 200,
  "token": "USD"
}

###

GET localhost:8000/balance?username=admin&password=admin

###
POST localhost:8000/withdraw/?username=admin&password=admin&amount=100&token=USD
Content-Type: application/json

{
  "username": "admin",
  "password": "admin",
  "amount": 100,
  "token": "USD"
}


###

GET localhost:8000/balance?username=admin&password=admin

###

#    type: str
#    product: str
#    amount: float
#    price: float
POST localhost:8000/place_order?username=admin&password=admin
Content-Type: application/json

{
  "username": "admin",
  "password": "admin",
  "amount": 1,
  "product": "BTC-USD",
  "price": 100,
  "type": "buy"
}
###


POST localhost:8000/deposit?username=user1&password=password1
Content-Type: application/json

{
  "username": "user1",
  "password": "password1",
  "amount": 5,
  "token": "BTC"
}
###

POST localhost:8000/place_order?username=user1&password=password1
Content-Type: application/json

{
  "username": "user1",
  "password": "password1",
  "amount": 1,
  "product": "BTC-USD",
  "price": 100,
  "type": "sell"
}
###

POST localhost:8000/add_liquidity/?username=user1&password=password1
Content-Type: application/json

{
  "amount_a": 1,
  "amount_b": 1000,
  "token_a": "BTC",
  "token_b": "USD"
}
